from PyQt5 import QtCore, QtWidgets
import webbrowser


class Ui_Form(object):
    url = "https://google.com"
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 141)
        self.artist_picture = QtWidgets.QLabel(Form)
        self.artist_picture.setGeometry(QtCore.QRect(0, 0, 176, 149))
        self.artist_picture.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.artist_picture.setAlignment(QtCore.Qt.AlignCenter)
        self.artist_picture.setObjectName("artist_picture")
        self.ticket_button = QtWidgets.QPushButton(Form)
        self.ticket_button.setGeometry(QtCore.QRect(700, 50, 121, 41))
        self.ticket_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ticket_button.setObjectName("ticket_button")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 0, 291, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.artist_info_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.artist_info_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.artist_info_layout.setContentsMargins(0, 0, 0, 0)
        self.artist_info_layout.setSpacing(0)
        self.artist_info_layout.setObjectName("artist_info_layout")
        self.artist_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.artist_label.sizePolicy().hasHeightForWidth())
        self.artist_label.setSizePolicy(sizePolicy)
        self.artist_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.artist_label.setTextFormat(QtCore.Qt.AutoText)
        self.artist_label.setWordWrap(True)
        self.artist_label.setObjectName("artist_label")
        self.artist_info_layout.addWidget(self.artist_label)
        self.event_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.event_label.sizePolicy().hasHeightForWidth())
        self.event_label.setSizePolicy(sizePolicy)
        self.event_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.event_label.setWordWrap(True)
        self.event_label.setObjectName("event_label")
        self.artist_info_layout.addWidget(self.event_label)
        self.location_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.location_label.sizePolicy().hasHeightForWidth())
        self.location_label.setSizePolicy(sizePolicy)
        self.location_label.setMinimumSize(QtCore.QSize(0, 0))
        self.location_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.location_label.setWordWrap(True)
        self.location_label.setObjectName("location_label")
        self.artist_info_layout.addWidget(self.location_label)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(490, 0, 201, 131))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.price_layout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.price_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.price_layout.setContentsMargins(0, 0, 0, 0)
        self.price_layout.setSpacing(0)
        self.price_layout.setObjectName("price_layout")
        self.date_label = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label.sizePolicy().hasHeightForWidth())
        self.date_label.setSizePolicy(sizePolicy)
        self.date_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.date_label.setWordWrap(True)
        self.date_label.setObjectName("date_label")
        self.price_layout.addWidget(self.date_label)
        self.lowest_price_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.lowest_price_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lowest_price_label.setObjectName("lowest_price_label")
        self.price_layout.addWidget(self.lowest_price_label)
        self.best_price_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.best_price_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.best_price_label.setObjectName("best_price_label")
        self.price_layout.addWidget(self.best_price_label)

        self.ticket_button.clicked.connect(lambda: webbrowser.open(self.url))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.artist_picture.setText(_translate("Form", "TextLabel"))
        self.ticket_button.setText(_translate("Form", "Buy a Ticket!"))
        self.artist_label.setText(_translate("Form", "TextLabel"))
        self.event_label.setText(_translate("Form", "TextLabel"))
        self.location_label.setText(_translate("Form", "TextLabel"))
        self.date_label.setText(_translate("Form", "TextLabel"))
        self.lowest_price_label.setText(_translate("Form", "TextLabel"))
        self.best_price_label.setText(_translate("Form", "TextLabel"))

